name: resume_radar
description: Resume Radar flutter application
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  http_mock_adapter: ^0.6.1
  flutter_launcher_icons:
    git:
      url: https://github.com/fluttercommunity/flutter_launcher_icons.git
      ref: 26fedcee4b0e6f7a85f65f1fb48834a21f57e970

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "images/png/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - animations/
    - images/svg/
    - images/png/
    - datasets/csv/

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  dio: ^5.4.3+1
  connectivity_plus: ^5.0.2
  permission_handler: ^11.0.1
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_bloc: ^8.1.1
  flutter_spinkit: ^5.1.0
  currency_text_input_formatter: ^2.1.7
  google_fonts: 6.1.0
  device_info_plus: ^9.0.2
  page_transition: ^2.0.9
  device_preview: ^1.1.0
  flutter_screenutil: ^5.6.1
  intl: ^0.18.0
  modal_bottom_sheet: ^3.0.0-pre
  flutter_local_notifications: ^17.0.1
  super_tooltip: ^2.0.7
  omni_datetime_picker: ^1.0.9
  pull_to_refresh: ^2.0.0
  flutter_udid: ^3.0.0
  pinput: ^5.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.7
  badges: ^3.1.2
  another_flushbar: ^1.12.30
  intl_phone_field: ^3.1.0
  image_picker: ^1.0.7
  image_cropper: ^5.0.1
  fl_country_code_picker: ^0.1.9+1
  url_launcher: ^6.2.4
  email_validator: ^2.1.17
  country_codes: ^2.2.0
  flutter_datetime_picker_plus: ^2.1.0
  file_picker: ^8.0.0+1
  open_filex: ^4.3.2
  package_info_plus: ^4.2.0
  path_provider: ^2.1.2
  path: ^1.8.3
  timezone: ^0.9.3
  web_socket_channel: ^2.4.0
  change_app_package_name: ^1.2.0
  sharpapi_flutter_client: ^1.2.0
  flutter_pdfview: ^1.3.2
  csv: ^6.0.0
  dash_chat_2: ^0.0.20
  flutter_gemini: ^2.0.5
  speech_to_text: ^6.6.0
  flutter_tts: ^4.0.2

  #Firebase
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.3